<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;osx-arm64</RuntimeIdentifiers>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>MoTuPerf.Platform</RootNamespace>
    <AssemblyName>MoTuPerf.Platform</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MoTuPerf.Core\MoTuPerf.Core.csproj" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MoTuPerf.Platform.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
